# Generated by Django 5.1.2 on 2024-10-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('ENGINEER', 'Engineer'), ('SALES', 'Sales')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('DEVELOPER', 'Developer'), ('ANALYST', 'Analyst')], max_length=30, null=True),
        ),
    ]
