# Generated by Django 5.1.2 on 2024-10-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_department_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('MANAGER', 'manager'), ('DEVELOPER', 'developer'), ('ANALYST', 'analyst')], max_length=30, null=True),
        ),
    ]
